set_property SRC_FILE_INFO {cfile:C:/Users/Weicheng/Documents/GitHub/CPET-563/Lecture9-example/example/example.srcs/constrs_1/new/Constraints.xdc rfile:../../../example.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN   E19        [get_ports LED]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD    LVCMOS33   [get_ports LED]
